#表明使用Druid连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://212.64.79.154:3310/wwmust?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: WANGwei2ming
#redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
sensitiveword:
  url: 212.64.79.154:8302